- key: S:oredict.crateGt.+
  priority: 5000
  repl: '{material}板条箱'
  token: item
  value: Crate of (?P<material>.+)
- key: S:gt.material.+
  priority: 1000
  repl: '{material}'
  token: item
  value: (?P<material>.+)
- key: S:gt.material.Any.+
  priority: 2000
  repl: 任意{material}
  token: item
  value: (?P<material>.+)
- key: S:fluid.molten.+
  priority: 1000
  repl: 熔融{material}
  token: item
  value: Molten (?P<material>.+)
- key: S:oredict.plantGtBlossom.+
  priority: 1000
  repl: '{material}花'
  token: item
  value: (?P<material>.+) Blossom
- key: S:oredict.plantGtBerry.+
  priority: 1000
  repl: '{material}莓'
  token: item
  value: (?P<material>.+) Berry
- key: S:oredict.plantGtWart.+
  priority: 1000
  repl: '{material}疣'
  token: item
  value: (?P<material>.+) Wart
- key: S:oredict.plantGtFiber.+
  priority: 1000
  repl: 生{material}丝
  token: item
  value: Raw (?P<material>.+) Fiber
- key: S:oredict.plantGtTwig.+
  priority: 1000
  repl: '{material}细枝'
  token: item
  value: (?P<material>.+) Twig
- key: S:oredict.bolt.+
  priority: 1000
  repl: '{material}螺栓'
  token: item
  value: (?P<material>.+) Bolt
- key: S:oredict.screw.+
  priority: 1000
  repl: '{material}螺丝'
  token: item
  value: (?P<material>.+) Screw
- key: S:oredict.stickLong.+
  priority: 1500
  repl: 长{material}杆
  token: item
  value: Long (?P<material>.+) Rod
- key: S:oredict.stick.+
  priority: 1000
  repl: '{material}杆'
  token: item
  value: (?P<material>.+) Rod
- key: S:oredict.casingSmall.+
  priority: 1000
  repl: '{material}外壳'
  token: item
  value: (?P<material>.+) Item Casing
- key: S:oredict.casingMachine.+
  priority: 1000
  repl: '{material}机械外壳'
  token: item
  value: (?P<material>.+) Machine Casing
- key: S:oredict.cell.+
  priority: 1000
  repl: '{material}单元'
  token: item
  value: (?P<material>.+) Cell
- key: S:oredict.foil.+
  priority: 1000
  repl: '{material}箔'
  token: item
  value: (?P<material>.+) Foil
- key: S:oredict.ring.+
  priority: 1000
  repl: '{material}环'
  token: item
  value: (?P<material>.+) Ring
- key: S:oredict.gearGt.+
  priority: 1000
  repl: '{material}齿轮'
  token: item
  value: (?P<material>.+) Gear
- key: S:oredict.gearGtSmall.+
  priority: 1500
  repl: 小型{material}齿轮
  token: item
  value: Small (?P<material>.+) Gear
- key: S:oredict.chemtube.+
  priority: 1000
  repl: '{material}试管'
  token: item
  value: Glass Tube containing (?P<material>.+)
- key: S:oredict.arrowGtWood.+
  priority: 1000
  repl: '{material}箭'
  token: item
  value: (?P<material>.+) Arrow
- key: S:oredict.lens.+
  priority: 1000
  repl: '{material}透镜'
  token: item
  value: (?P<material>.+) Lens
- key: S:oredict.arrowGtPlastic.+
  priority: 1000
  repl: 轻质{material}箭
  token: item
  value: Light (?P<material>.+) Arrow
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}箭头'
  token: item
  value: (?P<material>.+) Arrow Head
- key: S:oredict.tool.+
  priority: 2000
  repl: '{material}毛坯'
  token: item
  value: Raw (?P<material>.+)
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}斧头'
  token: item
  value: (?P<material>.+) Axe Head
- key: S:oredict.toolHead.+
  priority: 1500
  repl: '{material}双刃斧头'
  token: item
  value: (?P<material>.+) Double Axe Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}锤头'
  token: item
  value: (?P<material>.+) Hammer Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}锄头'
  token: item
  value: (?P<material>.+) Hoe Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: 表镶{material}镐头
  token: item
  value: (?P<material>.+) tipped Pickaxe Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}镐头'
  token: item
  value: (?P<material>.+) Pickaxe Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}犁头'
  token: item
  value: (?P<material>.+) Plow Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}镰刀片'
  token: item
  value: (?P<material>.+) Sense Blade
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}铲头'
  token: item
  value: (?P<material>.+) Spade Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}锹头'
  token: item
  value: (?P<material>.+) Shovel Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}凿子头'
  token: item
  value: (?P<material>.+) Chisel Head
- key: S:oredict.toolHead.+
  priority: 1100
  repl: '{material}建筑镐头'
  token: item
  value: (?P<material>.+) Construction Pickaxe Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}剑身'
  token: item
  value: (?P<material>.+) Sword Blade
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}圆锯片'
  token: item
  value: (?P<material>.+) Buzzsaw Blade
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}钻头'
  token: item
  value: (?P<material>.+) Drill Tip
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}锉刀头'
  token: item
  value: (?P<material>.+) File Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}电锯头'
  token: item
  value: (?P<material>.+) Chainsaw Tip
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}狼牙棒槌头'
  token: item
  value: (?P<material>.+) Mace Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}鹤嘴锄头'
  token: item
  value: (?P<material>.+) Mattock Head
- key: S:oredict.shuriken.+
  priority: 1000
  repl: '{material}飞镖'
  token: item
  value: (?P<material>.+) Shuriken
- key: S:oredict.spring.+
  priority: 1000
  repl: '{material}弹簧'
  token: item
  value: (?P<material>.+) Spring
- key: S:oredict.springSmall.+
  priority: 2000
  repl: 小型{material}弹簧
  token: item
  value: Small (?P<material>.+) Spring
- key: S:oredict.toolHead.+
  priority: 1100
  repl: '{material}万用铲头'
  token: item
  value: (?P<material>.+) Universal Spade Head
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}锯片'
  token: item
  value: (?P<material>.+) Saw Blade
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}螺丝刀头'
  token: item
  value: (?P<material>.+) Screwdriver Tip
- key: S:oredict.toolHead.+
  priority: 1000
  repl: '{material}扳手头'
  token: item
  value: (?P<material>.+) Wrench Tip
- key: S:oredict.wireFine.+
  priority: 1000
  repl: 精细{material}线缆
  token: item
  value: Fine (?P<material>.+) Wire
- key: S:oredict.rotor.+
  priority: 1000
  repl: '{material}转子'
  token: item
  value: (?P<material>.+) Rotor
- key: S:oredict.round.+
  priority: 1000
  repl: '{material}垫片'
  token: item
  value: (?P<material>.+) Round
- key: S:oredict.minecartWheels.+
  priority: 1000
  repl: '{material}车轮'
  token: item
  value: (?P<material>.+) Cart Wheels
- key: S:oredict.chain.+
  priority: 1000
  repl: '{material}锁链'
  token: item
  value: Chains of (?P<material>.+)
- key: S:oredict.link.+
  priority: 1000
  repl: '{material}链环'
  token: item
  value: Link of (?P<material>.+)
- key: S:oredict.railGt.+
  priority: 1000
  repl: '{material}导轨'
  token: item
  value: (?P<material>.+) Rail
- key: S:oredict.scrapGt.+
  priority: 1000
  repl: '{material}废料'
  token: item
  value: (?P<material>.+) Scrap
- key: S:oredict.rockGt.+
  priority: 1000
  repl: 含{material}岩石
  token: item
  value: (?P<material>.+) bearing Rock

# Ores
- key: S:oredict.ore.+
  priority: 2000
  repl: '{stratum_prefix}{material}矿石'
  token: ore
  value: (?P<stratum_prefix>[^ ]+) (?P<material>.+) (Ore|Stone)
- key: S:oredict.ore.+
  priority: 2000
  repl: '{material}{stratum_suffix}'
  token: ore
  value: (?P<stratum_suffix>[^ ]+) (?P<material>.+) (Ore|Stone)


- key: S:oredict.block.+
  priority: 2000
  repl: '{material}块'
  token: item
  value: Block of (?P<material>.+)
- key: S:oredict.blockDust.+
  priority: 3000
  repl: '{material}粉块'
  token: item
  value: Block of (?P<material>.+) (Dust|Powder)$
- key: S:oredict.blockDust.+
  priority: 2900
  repl: '{material}粉块'
  token: item
  value: Block of (?P<material>.+)$
- key: S:oredict.blockIngot.+
  priority: 3000
  repl: '{material}锭块'
  token: item
  value: Block of (?P<material>.+) (Ingot)?$
- key: S:oredict.blockPlate.+
  priority: 3000
  repl: '{material}板块'
  token: item
  value: Block of (?P<material>.+) Plates?$
- key: S:oredict.blockSolid.+
  priority: 3000
  repl: 铸造{material}块
  token: item
  value: Block of solid (?P<material>.+)$
- key: S:oredict.(block|dust|crateGt).+
  priority: 500
  repl: '{material}粉'
  token: item
  value: (?P<material>.+) (Dust|Powder)
- key: S:oredict.dustSmall.+
  priority: 2000
  repl: 小堆{material}
  token: item
  value: Small Pile of (?P<material>.+)$
- key: S:oredict.dustTiny.+
  priority: 2000
  repl: 小撮{material}
  token: item
  value: Tiny Pile of (?P<material>.+)$
- key: S:oredict.dustDiv72.+
  priority: 2000
  repl: 1/72份{material}
  token: item
  value: 1/72nd of a Pile of (?P<material>.+)$
- key: S:oredict.dustPure.+
  priority: 1000
  repl: 纯净{material}
  token: item
  value: Purified Pile of (?P<material>.+)$
- key: S:oredict.dustImpure.+
  priority: 1000
  repl: 含杂{material}
  token: item
  value: Impure Pile of (?P<material>.+)$
- key: S:oredict.(block|plate|crateGt).+
  priority: 500
  repl: '{material}板'
  token: item
  value: (?P<material>.+) Plate
- key: S:oredict.nugget.+
  priority: 1000
  repl: '{material}粒'
  token: item
  value: (?P<material>.+) Nugget
- key: S:oredict.chunkGt.+
  priority: 1000
  repl: '{material}小块'
  token: item
  value: (?P<material>.+) Chunk
- key: S:oredict.(block|ingot|crateGt).+
  priority: 500
  repl: '{material}锭'
  token: item
  value: (?P<material>.+) Ingot
- key: S:oredict.*[Gg]em.*
  priority: 400
  repl: 结晶{material}
  token: item
  value: Crystalline (?P<material>.+)
- key: S:oredict.ingotHot.+
  priority: 1000
  repl: 热{material}锭
  token: item
  value: Hot (?P<material>.+) Ingot
- key: S:oredict.ingotDouble.+
  priority: 1000
  repl: 两重{material}锭
  token: item
  value: Double (?P<material>.+) Ingot
- key: S:oredict.ingotTriple.+
  priority: 1000
  repl: 三重{material}锭
  token: item
  value: Triple (?P<material>.+) Ingot
- key: S:oredict.ingotQuadruple.+
  priority: 1000
  repl: 四重{material}锭
  token: item
  value: Quadruple (?P<material>.+) Ingot
- key: S:oredict.ingotQuintuple.+
  priority: 1000
  repl: 五重{material}锭
  token: item
  value: Quintuple (?P<material>.+) Ingot
- key: S:oredict.+[dD]ense.+
  priority: 2000
  repl: 致密{material}
  token: item
  value: Dense (?P<material>.+)
- key: S:oredict.+[qQ]uadruple.+
  priority: 2000
  repl: 高强度{material}
  token: item
  value: Reinforced (?P<material>.+)
- key: S:oredict.+[dD]ouble.+
  priority: 2000
  repl: 加强{material}
  token: item
  value: Robust (?P<material>.+)
- key: S:oredict.plate(Gem)?Tiny.+
  priority: 2000
  repl: 小块{material}
  token: item
  value: Tiny (?P<material>.+)
- key: S:oredict.plateCurved.+
  priority: 2000
  repl: 弯曲{material}
  token: item
  value: Curved (?P<material>.+)
- key: S:oredict.plateDouble.+
  priority: 2000
  repl: 两重{material}
  token: item
  value: Double (?P<material>.+)
- key: S:oredict.plateTriple.+
  priority: 2000
  repl: 三重{material}
  token: item
  value: Triple (?P<material>.+)
- key: S:oredict.plateQuadruple.+
  priority: 2000
  repl: 四重{material}
  token: item
  value: Quadruple (?P<material>.+)
- key: S:oredict.plateQuintuple.+
  priority: 2000
  repl: 五重{material}
  token: item
  value: Quintuple (?P<material>.+)
- key: S:oredict.crushed.+
  priority: 1000
  repl: 粉碎{material}矿石
  token: item
  value: Crushed (?P<material>.+) Ore
- key: S:oredict.crushedCentrifuged.+
  priority: 1100
  repl: 离心{material}矿石
  token: item
  value: Refined (?P<material>.+) Ore
- key: S:oredict.crushedPurified.+
  priority: 1100
  repl: 纯净{material}矿石
  token: item
  value: Purified (?P<material>.+) Ore
- key: S:oredict.crushedTiny.+
  priority: 1050
  repl: 小撮粉碎{material}矿石
  token: item
  value: Tiny Crushed (?P<material>.+) Ore
- key: S:oredict.crushedPurifiedTiny.+
  priority: 1200
  repl: 小撮纯净{material}矿石
  token: item
  value: Tiny Purified (?P<material>.+) Ore
- key: S:oredict.crushedCentrifugedTiny.+
  priority: 1200
  repl: 小撮离心{material}矿石
  token: item
  value: Tiny Refined (?P<material>.+) Ore
- key: S:gt.block.(beam|log|planks).+
  priority: 1500
  repl: '{material} (防火)'
  token: item
  value: (?P<material>.+) \(Fireproof\)
- key: S:gt.block.beam.+
  priority: 1000
  repl: '{material}梁'
  token: item
  value: (?P<material>.+) Beam
- key: S:gt.block.log.+
  priority: 1000
  repl: '{material}原木'
  token: item
  value: (?P<material>.+) Log
- key: S:gt.block.planks.+
  priority: 1000
  repl: '{material}木板'
  token: item
  value: (?P<material>.+) Planks?
- key: S:gt.block.planks.+
  priority: 1000
  repl: '{material}木半砖'
  token: item
  value: (?P<material>.+) Slab
- key: S:gt.multitileentity.+
  priority: 1000
  repl: '{material} (青铜)'
  token: item
  value: (?P<material>.+) \(Bronze\)
- key: S:gt.multitileentity.+
  priority: 1000
  repl: '{material} (钢)'
  token: item
  value: (?P<material>.+) \(Steel\)
- key: S:gt.multitileentity.+
  priority: 1000
  repl: '{material} (钛)'
  token: item
  value: (?P<material>.+) \(Titanium\)
- key: S:gt.multitileentity.+
  priority: 1000
  repl: '{material} (钨钢)'
  token: item
  value: (?P<material>.+) \(Tungstensteel\)
- key: S:gt.multiitem.bumblebee.+
  priority: 2000
  repl: '{material} (死亡)'
  token: item
  value: (?P<material>.+) \(Dead\)
- key: S:gt.multiitem.bumblebee.+
  priority: 2000
  repl: '{material} (已扫描)'
  token: item
  value: (?P<material>.+) \(Scanned\)
- key: S:gt.multiitem.bumblebee.+
  priority: 2000
  repl: '{material} (死亡且已扫描)'
  token: item
  value: (?P<material>.+) \(Dead & Scanned\)
- key: S:gt.multiitem.bumblebee.+
  priority: 1500
  repl: 雄性{material}
  token: item
  value: (?P<material>.+) Drone
- key: S:gt.multiitem.bumblebee.+
  priority: 1500
  repl: 雌性{material}
  token: item
  value: (?P<material>.+) Princess
- key: S:gt.multiitem.bumblebee.+
  priority: 1500
  repl: '{material}蜂后'
  token: item
  value: (?P<material>.+) Queen
- key: S:gt.multiitem.bumblebee.+
  priority: 1000
  repl: '{material}大黄蜂'
  token: item
  value: Bumble (?P<material>.+)
- key: S:gt.multiitem.bumblebee.+
  priority: 1000
  repl: '{material}大黄蜂'
  token: item
  value: (?P<material>.+) Bumblebee
- key: S:gt.block.concrete.+
  priority: 1000
  repl: '{material}混凝土'
  token: item
  value: (?P<material>.+) Concrete
- key: S:gt.block.concrete.+
  priority: 1000
  repl: '{material}强化混凝土'
  token: item
  value: (?P<material>.+) Reinforced Concrete
- key: S:gt.block.concrete.+
  priority: 2000
  repl: '{material}半砖'
  token: item
  value: (?P<material>.+) Slab
- key: S:fluid.cfoam.+
  priority: 2000
  repl: 高级{material}
  token: item
  value: Advanced (?P<material>.+)
- key: S:fluid.cfoam.+
  priority: 1000
  repl: '{material}建筑泡沫'
  token: item
  value: (?P<material>.+) C-Foam
- key: S:oredict.gemChipped.+
  priority: 1000
  repl: 碎裂的{material}
  token: item
  value: Chipped (?P<material>.+)\s*(Crystal)?
- key: S:oredict.gemExquisite.+
  priority: 1000
  repl: 精美的{material}
  token: item
  value: Exquisite (?P<material>.+)\s*(Crystal)?
- key: S:oredict.gemFlawed.+
  priority: 1000
  repl: 有瑕疵的{material}
  token: item
  value: Flawed (?P<material>.+)\s*(Crystal)?
- key: S:oredict.gemFlawless.+
  priority: 1000
  repl: 无瑕的{material}
  token: item
  value: Flawless (?P<material>.+)\s*(Crystal)?
- key: S:oredict.gemLegendary.+
  priority: 1000
  repl: 传奇{material}
  token: item
  value: Legendary (?P<material>.+)\s*(Crystal)?
- key: S:qwertech.machines.+
  priority: 1000
  repl: '{material}合成站'
  token: item
  value: (?P<material>.+) Crafting Table
- key: S:qwertech.machines.+
  priority: 1000
  repl: '{material}合成砧'
  token: item
  value: (?P<material>.+) Crafting Anvil
- key: S:qwertech.machines.+
  priority: 1000
  repl: '{material}升级台'
  token: item
  value: (?P<material>.+) Upgrade Desk
- key: S:qwertech.armor.upgrades.+
  priority: 1000
  repl: 小型{material}弹簧组
  token: item
  value: Dual (?P<material>.+) Springs
- key: S:gt.multitileentity.+
  priority: 1000
  repl: "{item_has_energy_tier} ({energy_tier})"
  token: machine
  value: (?P<item_has_energy_tier>.+) \((?P<energy_tier>.+)\)
